name: Full Release Process

on:
  push:
    tags:
      - 'v*'

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.draft.outputs.id }}
    steps:
      - uses: actions/checkout@v4
      - id: draft
        name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          generate_release_notes: true

  build-release:
    needs: create-draft-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-
      - run: npm install
      - run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs:
      - create-draft-release
      - build-release
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Jaeminst/zet-board/releases/${{ needs.create-draft-release.outputs.release_id }} \
            -F draft=false \
            -F prerelease=false 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}