type ipcProfile = 'init-profiles'
                | 'add-profile'
                | 'delete-profile'
                | 'update-profile'
                | 'assume-role'
                | 'session-expired'
                | 'default-profile'
