type ipcProfile =
  |'init-profiles'
  | 'add-profile'
  | 'delete-profile'
  | 'update-profile'
  | 'assume-role'
  | 'session-expired'
  | 'default-profile'
  | 'get-profileList'
  | 'set-profileList'
  | 'get-profileSession'
  | 'set-profileSession'
  | 'get-profileSessions'
  | 'set-profileSessions'
